language: java

jdk:
  - oraclejdk8

script: mvn install --batch-mode --show-version

deploy:
  - provider: script
    script: bash src/main/build/mvndeploy.sh
    skip_cleanup: true
    on:
      repo: fxnn/brainfuck
      branch: master
  - provider: script
    script: bash src/main/build/mvndeploy.sh
    skip_cleanup: true
    on:
      repo: fxnn/brainfuck
      tags: true
  - provider: script
    script: bash src/main/build/jacoco-report.sh

cache:
  directories:
    - ~/.m2/repository